FROM golang:alpine

RUN apk update && apk add git

RUN mkdir -p /go/src/github.com/byuoitav
ADD . /go/src/github.com/byuoitav/atlona-microservice

WORKDIR /go/src/github.com/byuoitav/atlona-microservice
RUN go get -d -v
RUN go install -v

CMD ["/go/bin/atlona-microservice"]

EXPOSE 8015
